html(document.body)
	.input(store.mayte).$
	.input(store.ho).$
	.input(store.ten).$
	.input(store.gioitinh).$
	.input(store.ngaysinh).$
	.br
	.input(store.diachi).$
	.input(store.sodienthoai).$
	.input(store.nghenghiep).$
